### ISSUE TITLE
Error by building an Qt based project

### ISSUE THREAD

**Issue by ixtz** [mayah/tinytoml#1]
Hey! I want to use TinyTOML in my Qt project, I've added the line ``QMAKE_CXXFLAGS += -std=c++11`` to set the flags for C++11.

Now when I start building I get the following error:
```
In file included from src/core/project.cpp:29:0:
src/core/../../externals/tinytoml/toml.h: In static member function 'static bool toml::Parser::parseTime(const string&, toml::Value*)':
src/core/../../externals/tinytoml/toml.h:829:58: error: 'timegm' was not declared in this scope
     *v = std::chrono::system_clock::from_time_t(timegm(&t));
                                                          ^
mingw32-make[1]: *** [debug/project.o] Error 1
Makefile.Debug:143: recipe for target 'debug/project.o' failed
mingw32-make[1]: Leaving directory 'C:/arden'
mingw32-make: *** [debug] Error 2
makefile:34: recipe for target 'debug' failed
[Finished in 2.5s]
```

How can I fix this?

~ Jan

**Comment by mayah** [comment]
Windows platform? Maybe Windows does not have timegm.
According to http://stackoverflow.com/questions/16647819/timegm-cross-platform, _mkgmtime will work. 

Try
#define timegm _mkgmtime

**Comment by i5jan** [comment]
Works fine with the define directive, thanks!

**Comment by i5jan** [comment]
Sorry that I reopen but that gives me an new error, I don't know if this is based on the compiler (cause of linking) or on the header. I wrote simply this, to check if my files are valid:

```cpp
/* at least lets check if the TOML based files are all valid */
			std::ifstream r_ifs(_r_file.toStdString().c_str());
			toml::Parser r_parser(r_ifs);
			toml::Value r_val = r_parser.parse();
			if (r_val.valid())
			{
				/* everything is fine */
				printf("root file is valid TOML\n");
			}
```

This gives me
```
debug/project.o: In function `ZN4toml6Parser9parseTimeERKSsPNS_5ValueE':
c:\arden/src/core/../../externals/tinytoml/toml.h:830: undefined reference to `_mkgmtime'
```

**Comment by mayah** [comment]
Since it's a link error, the code itself should be ok.

You're using mingw 32bit version? I found this one.
http://sourceforge.net/p/mingw-w64/bugs/473/
If this is true, It's mingw bug, I believe. You can follow this article to fix.

Or, try another approach.
Try to add timegm which is also mentioned in
http://stackoverflow.com/questions/16647819/timegm-cross-platform
by yourself? I didn't check it, but the writer says it works on Windows. I'm not sure it also works on mingw environment.

time_t timegm(struct tm * a_tm)
{
    time_t ltime = mktime(a_tm);
    struct tm tm_val;
    gmtime_s(&tm_val, &ltime);
    int offset = (tm_val.tm_hour - a_tm->tm_hour);
    if (offset > 12)
    {
        offset = 24 - offset;
    }
    time_t utc = mktime(a_tm) - offset * 3600;
    return utc;
}

**Comment by i5jan** [comment]
Yep using MinGW 32-bit but the version which was installed when installing Qt, so rebuilding would not work.

**Comment by mayah** [comment]
Then, try to define timegm() by yourself. Doesn't it work?

**Comment by mayah** [comment]
No update, closing.
