### ISSUE TITLE
Support for ints in hex/binary format?

### ISSUE THREAD

**Issue by erichargitt** [mayah/tinytoml#24]
Hello,

Love this parser. Do you have plans to support hex/binary inputs for integers? I can write it if you think it's a good idea. Let me know.

**Comment by mayah** [comment]
This parser implements TOML specification. As long as TOML spec supports hex/binary inputs, I will have a plan. But currently there is no such spec?

**Comment by mayah** [comment]
See also https://github.com/toml-lang/toml/issues/409

**Comment by erichargitt** [comment]
Oh haha. I didn't know toml specified that. Well, thanks for your work on this.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by mayah** [comment]
Closing
