### ISSUE TITLE
Issue with nested array

### ISSUE THREAD

**Issue by quantizz** [mayah/tinytoml#3]
Hello! I’m trying to parse nested arrays but without success.
Example:

[[widgets]]
  type = "image"
  width = 1000

  [[widgets.topics]]
    topic = "some"
    count = 3

  [[widgets.topics]]
     topic = "something"
    count = 4

I am getting "Error: line 27: error when parsing group key" when I check if it's valid.
Line 27 in my toml file is "topic = "some"".

**Comment by mayah** [comment]
Thanks for the error report. I'll check it soon

**Comment by mayah** [comment]
Hmm, I've added the same test case, but succeeded.
https://github.com/mayah/tinytoml/commit/fb525574d77c5ab2d3cdd3a0ac5440da9f73cfc9

Could you check your toml file again?
The error message is "error when parsing group key", so probably your group key ([foo] or [[foo]]) might have an invalid format. Could you check line 27, line 26, or group key before line 27?

If you can provide your entire toml file, I might be able to check more.

**Comment by quantizz** [comment]
Thank you very much for being so quick in responding to the issue.
I tested with your test toml file and I still got the same error. The problem was with my tinytoml.h file that was from June. I upgraded to the most recent version and the error is gone. Should have looked at that first.

Thank you again.
