### ISSUE TITLE
support compilation with exception disabled

### ISSUE THREAD

**Issue by HongxuChen** [mayah/tinytoml#33]
Given `failwith` is the only function incompatible when `-fno-exceptions` is specified, I think it would be great to provide a version where exceptions are disabled. The compilation condition can be guarded by a macro guard.

**Comment by mayah** [comment]
To achieve that,
  - we have to change the interface to return an error
  - or abort immediately in failwith.

Actually I'm also considering an exception is harmful, but I'm not sure it's a good decision for now.

**Comment by HongxuChen** [comment]
Personally I prefer the immediate abortion since for now it introduces the minimal changes.

**Comment by mayah** [comment]
Now you can define your own failwith.
