### ISSUE TITLE
Suggestion: rename include/toml to include/tinytoml

### ISSUE THREAD

**Issue by cvilas** [mayah/tinytoml#35]
There seems to be a convention to name top level path of header files to match the corresponding library name. This is followed by many other projects, eg: [opencv](https://github.com/opencv/opencv/tree/master/include), [gsl](https://github.com/Microsoft/GSL/tree/master/include). Would you consider doing the same for this library too? 

Thanks for this project. This is my preferred library for parsing configuration files in my own projects.

**Comment by mayah** [comment]
It might be a convention, but there are lots of exceptions e.g. [jsoncpp](https://github.com/open-source-parsers/jsoncpp/tree/master/include/json).

I feel it's too late to change the name. If I can change backward compatibility, I'd like to change a lot of things, but currently I don't want to go that way.

The lucky thing is this library is header-only. So it's easy to rename the directory for your project.

**Comment by cvilas** [comment]
Fair enough! Thanks.
