### ISSUE TITLE
Cut a tagged release

### ISSUE THREAD

**Issue by btmcg** [mayah/tinytoml#39]
Hello,

I'd like to use your code in a personal project. Would you be able to tag a release so that I can more-easily avoid breaking changes/updates? I'd like to pin my project to a specific version of your library and I'd like to avoid embedding 'master' or an ugly hash in my build system.

Thanks!

**Comment by mayah** [comment]
tagged https://github.com/mayah/tinytoml/releases/tag/v0.4
