### ISSUE TITLE
Comparison operator

### ISSUE THREAD

**Issue by RobertBColton** [mayah/tinytoml#9]
Hello, I am wondering if it would be possible to add support for comparing toml::Value using the equality operators? toml::Value has some type information to cast and do the comparison. It would also be nice to have .compare_as<T,T>() for comparisons.

**Comment by mayah** [comment]
Ah, I haven't defined any operator==(), so currently we cannot compare values. It won't be hard to add operator==() and operator!=().

For compare_as(), how do you use? Something like compare_as<int>(a, b) when a and b are toml::Value ? If so, a.as<int>() < b.as<int>() or something?

**Comment by RobertBColton** [comment]
I would suggest the following as a static method:
```c++
toml::Value::compare_as<int,bool>(myValue1,myvalue2);
```

**Comment by mayah** [comment]
I'm still wondering the behavior of compare_as().

What should happen if type error?

What is the result? If it returns true when the values are the same, equal_as() would be better name, and operator== is the best for this purpose.

I feel user preference would be different, so it might be good a user defines their one by themself.

Anyway, I'll add operator== and operator!= today (maybe 12~14 hours later)

**Comment by RobertBColton** [comment]
@mayah Thank you so much! == and != are all we really need actually. We're making an entity-component game engine and need to check if the value actually changes before firing an update event.

As far as compare_as goes, I was thinking along the lines of std::compare:
http://www.cplusplus.com/reference/string/string/compare/

And so you wouldn't have to overload every operator, a third argument could be a function object with a boxed operator. Something like how STL comparators work:
http://stackoverflow.com/questions/24689092/how-does-the-compare-function-in-stdmap-in-c-work-if-it-is-reflexively-true

But we have no foreseeable need for such a feature, and would be happy to overload the operators ourselves. This is simply all I need for now with our Qt engine:
```c++
	// TODO: Only emit the signal when the property actually changes.
	component->properties[name] = value;
	emit propertyChanged(name, value);
	std::cout << "helloo " << value << std::endl;
```

**Comment by mayah** [comment]
Added operator==, operator!=, and operator[]. So, closing.

Currently I don't have any plan to add something like std::compare, since there is no natural order for toml::Value. If you have a strong demand for compare() method, feel free to file a new issue.

**Comment by RobertBColton** [comment]
Sounds great, it's working perfect here, thanks again!
